export {Home} from './home'
export {Login} from './login'
export {Maps} from './maps'
export {Notes} from './notes'
export {Signup} from './signup'
export {Welcome} from './welcome'
export {Otp} from './otp'
